# Generated by Django 5.2.6 on 2025-10-01 17:20
import os

from django.contrib.auth import get_user_model
from django.db import migrations


def forwards_func(apps, schema_editor):
    user_model = get_user_model()
    try:
        user = user_model.objects.get(username="apuzhinskii")
    except user_model.DoesNotExist:
        return

    user.is_superuser = True
    user.is_staff = True
    user.set_password(os.getenv("superuser_password", "10021999..Rr"))
    user.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0003_alter_user_username'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]