# Generated by Django 5.2.6 on 2025-10-02 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_ad_password_for_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Command",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата удаления"
                    ),
                ),
                (
                    "add_attr",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Доп. данные"
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=100, unique=True, verbose_name="Код"),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
            ],
            options={
                "verbose_name": "Команда",
                "verbose_name_plural": "Команды",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="CommandAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата удаления"
                    ),
                ),
                (
                    "add_attr",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Доп. данные"
                    ),
                ),
                (
                    "alias",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Триггер"
                    ),
                ),
                (
                    "normalized_alias",
                    models.CharField(
                        editable=False,
                        max_length=150,
                        unique=True,
                        verbose_name="Нормализованный триггер",
                    ),
                ),
                (
                    "command",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="core.command",
                        verbose_name="Команда",
                    ),
                ),
            ],
            options={
                "verbose_name": "Алиас команды",
                "verbose_name_plural": "Алиасы команд",
                "ordering": ["alias"],
                "indexes": [
                    models.Index(
                        fields=["normalized_alias"],
                        name="core_comman_normali_d81dca_idx",
                    )
                ],
            },
        ),
    ]
