# Generated by Django 5.2.6 on 2025-10-01 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('alias', models.CharField(max_length=100, unique=True, verbose_name='Альтернативное название')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='expenses.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
