# Generated by Django 5.2.6 on 2025-10-01 20:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_add_base_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['user', 'category'], 'verbose_name': 'Бюджет', 'verbose_name_plural': 'Бюджеты'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='categoryalias',
            options={'ordering': ['alias'], 'verbose_name': 'Алиас категории', 'verbose_name_plural': 'Алиасы категорий'},
        ),
        migrations.AddIndex(
            model_name='categoryalias',
            index=models.Index(fields=['alias'], name='expenses_ca_alias_db6689_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', 'created_at'], name='expenses_ex_user_id_88f6c0_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['category', 'created_at'], name='expenses_ex_categor_2b827c_idx'),
        ),
    ]
