# Generated by Django 5.2.6 on 2025-10-01 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_add_new_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='add_attr',
            field=models.JSONField(blank=True, default=dict, verbose_name='Доп. данные'),
        ),
        migrations.AddField(
            model_name='category',
            name='add_attr',
            field=models.JSONField(blank=True, default=dict, verbose_name='Доп. данные'),
        ),
        migrations.AddField(
            model_name='categoryalias',
            name='add_attr',
            field=models.JSONField(blank=True, default=dict, verbose_name='Доп. данные'),
        ),
        migrations.AddField(
            model_name='expense',
            name='add_attr',
            field=models.JSONField(blank=True, default=dict, verbose_name='Доп. данные'),
        ),
    ]
