# Generated by Django 5.2.6 on 2025-10-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0010_migrate_it_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='chat_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Chat ID'),
        ),
    ]
